name: Self-Healing CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/self-healing-app:latest ./app

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push to DockerHub
        run: docker push vivekbommalla1251/self-healing-app:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull vivekbommalla1251/self-healing-app:latest
            docker stop myapp || true
            docker rm myapp || true
            docker run -d --name myapp -p 5000:5000 vivekbommalla1251/self-healing-app:latest
            echo "✅ Deployed successfully!"